import type { GenrePreset, BeatCell } from "./types";

export const DEFAULT_BPM = 60;
export const MIN_BPM = 10;
export const MAX_BPM = 240;
export const MAX_MEASURES = 20;

const e = (
  b: BeatCell["baixo"],
  m: BeatCell["meio"],
  c: BeatCell["cima"],
): BeatCell => ({
  baixo: b,
  meio: m,
  cima: c,
});

export const GENRE_PRESETS: GenrePreset[] = [
  {
    name: "Livre",
    bpm: DEFAULT_BPM,
    timeSignature: { beats: 4, subdivision: 4 },
    measures: 1,
    accents: [1],
    cells: Array.from({ length: 16 }, () => e(null, null, null)),
  },
  {
    name: "Choro",
    bpm: DEFAULT_BPM,
    timeSignature: { beats: 2, subdivision: 4 },
    measures: 2,
    accents: [2, 4],
    cells: [
      e("P", null, null),
      e(null, null, "F"),
      e(null, "T", null),
      e(null, null, "F"),
      e("P", null, null),
      e(null, null, "F"),
      e(null, "T", null),
      e(null, null, "F"),
      e("P", null, null),
      e(null, null, "F"),
      e(null, "T", null),
      e(null, null, "F"),
      e("P", null, null),
      e(null, null, "F"),
      e(null, "T", null),
      e(null, null, "F"),
    ],
  },
  {
    name: "Samba",
    bpm: DEFAULT_BPM,
    timeSignature: { beats: 2, subdivision: 4 },
    measures: 2,
    accents: [2, 4],
    cells: [
      e("P", null, null),
      e(null, null, "F"),
      e(null, "Pm", null),
      e(null, null, "F"),
      e(null, null, "D"),
      e(null, null, "F"),
      e(null, "T", null),
      e(null, null, "F"),
      e("P", null, null),
      e(null, null, "F"),
      e(null, "Pm", null),
      e(null, null, "F"),
      e(null, null, "D"),
      e(null, null, "F"),
      e(null, "T", null),
      e(null, null, "F"),
    ],
  },
  {
    name: "Baião",
    bpm: DEFAULT_BPM,
    timeSignature: { beats: 2, subdivision: 4 },
    measures: 2,
    accents: [1, 3],
    cells: [
      e("P", null, null),
      e(null, null, null),
      e(null, "Dm", null),
      e(null, null, null),
      e(null, null, "D"),
      e(null, null, null),
      e(null, "T", null),
      e(null, null, null),
      e("P", null, null),
      e(null, null, null),
      e(null, "Dm", null),
      e(null, null, null),
      e("H", null, null),
      e(null, null, null),
      e(null, "T", null),
      e(null, null, null),
    ],
  },
  {
    name: "Frevo",
    bpm: DEFAULT_BPM,
    timeSignature: { beats: 2, subdivision: 4 },
    measures: 2,
    accents: [1, 3],
    cells: [
      e("P", null, "F"),
      e(null, null, "F"),
      e(null, "T", "F"),
      e(null, null, "F"),
      e(null, "Pm", "F"),
      e(null, null, "F"),
      e(null, "T", "F"),
      e(null, null, "F"),
      e("P", null, "F"),
      e(null, null, "F"),
      e(null, "T", "F"),
      e(null, null, "F"),
      e(null, "Pm", "F"),
      e(null, null, "F"),
      e(null, "T", "F"),
      e(null, null, "F"),
    ],
  },
  {
    name: "Maracatu",
    bpm: DEFAULT_BPM,
    timeSignature: { beats: 4, subdivision: 4 },
    measures: 1,
    accents: [1],
    cells: [
      e("P", null, null),
      e(null, null, "F"),
      e(null, "T", null),
      e(null, null, "F"),
      e(null, null, "D"),
      e(null, null, "F"),
      e("H", "T", null),
      e(null, null, "F"),
      e("P", null, null),
      e(null, null, "F"),
      e(null, "T", null),
      e(null, null, "F"),
      e(null, null, "D"),
      e(null, null, "F"),
      e("H", "T", null),
      e(null, null, "F"),
    ],
  },
];
